---

# WAN  Tenants Network Services

overlay_rt_type:
  admin_subfield: bgp_as

overlay_rd_type:
  admin_subfield: vtep_loopback

tenants: # dynamic_key: network_services
  - name: srtcSmall
    vrfs:
      - name: default
        vrf_vni: 101
      - name: prod
        vrf_vni: 1
