---

# paypal1-Site-DC1-1 Router Configuration

host_custom_structured_static_routes:
  - vrf: default
    destination_address_prefix: 0.0.0.0/0
    gateway: 172.16.110.2

host_custom_structured_loopback_interfaces:
  - name: Loopback1
    vrf: prod
    ip_address: 10.254.110.1/32

host_custom_structured_router_path_selection:
  load_balance_policies:
    - name: LB-PROD-AVT-POLICY-Critical-APP
      lowest_hop_count: True
      path_groups:
        - name: internet
          priority: 1

custom_structured_configuration_ethernet_interfaces:
- name: Ethernet1
  mtu: 1600
  flow_tracker:
    hardware: FLOW-TRACKER

- name: Ethernet4
  ip_address: 10.1.110.3/24
  shutdown: false
  vrf: prod
  type: routed
  load_interval: 10
  flow_tracker:
    hardware: FLOW-TRACKER


host_custom_structured_router_bgp:
  router_id: 192.168.110.1
  vrfs:
    - name: default
      router_id: 192.168.110.1
    - name: prod
      router_id: 192.168.110.1
