---

# paypal1-Site-CLD-1 Router Configuration

host_custom_structured_static_routes:
  - vrf: default
    destination_address_prefix: 0.0.0.0/0
    gateway: 172.16.100.2
  # - vrf: default
  #   destination_address_prefix: 10.240.0.0/16
  #   gateway: 10.240.100.2


host_custom_structured_loopback_interfaces:
  - name: Loopback1
    vrf: prod
    ip_address: 10.254.100.1/32

custom_structured_configuration_ethernet_interfaces:
- name: Ethernet1
  mtu: 1600
  flow_tracker:
    hardware: FLOW-TRACKER
- name: Ethernet2
  mtu: 1700
  flow_tracker:
    hardware: FLOW-TRACKER
- name: Ethernet4
  ip_address: 10.1.100.3/24
  shutdown: false
  vrf: prod
  type: routed
  flow_tracker:
    hardware: FLOW-TRACKER


host_custom_structured_router_bgp:
  router_id: 192.168.100.1
  vrfs:
    - name: default
      router_id: 192.168.100.1
    - name: prod
      router_id: 192.168.100.1

