---

host_custom_structured_static_routes:
  - vrf: default
    destination_address_prefix: 0.0.0.0/0
    gateway: 172.16.99.18

custom_structured_configuration_ethernet_interfaces:
- name: Ethernet1
  flow_tracker:
    hardware: FLOW-TRACKER
- name: Ethernet2
  flow_tracker:
    hardware: FLOW-TRACKER

